swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/transactions/{accountId}/{year}/{month}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Get User Transactions for a Month and Account
      description: API for fetching all transactions of a user for a specific month and account
      parameters:
        - in: path
          name: accountId
          type: string
          required: true
          description: ID of the account
        - in: path
          name: year
          type: integer
          required: true
          description: Year of the transactions
        - in: path
          name: month
          type: integer
          required: true
          description: Month of the transactions (1-12)
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionWithId'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/transactions/{transactionId}/comment:
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update Transaction Comment
      description: API for add the comment of a specific transaction
      parameters:
        - in: path
          name: transactionId
          type: string
          required: true
          description: ID of the transaction
        - in: body
          name: body
          description: add Transaction Comment Payload
          required: true
          schema:
            $ref: '#/definitions/AddTransactionComment'
      responses:
        '200':
          description: Transaction comment add successfully
          schema:
            $ref: '#/definitions/AddTransactionComment'
        '400':
          description: Invalid Fields
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
  /user/transactions/{transactionId}/DeletComment:
    delete:
        security:
        - Bearer: []
        tags:
        - User Module
        summary: Delete Transaction Comment
        description: API for deleting the comment of a specific transaction
        parameters:
        - in: path
            name: transactionId
            type: string
            required: true
            description: ID of the transaction
        responses:
        '200':
            description: Transaction comment deleted successfully
        '404':
            description: Transaction not found
        '500':
            description: Internal Server Error
  /user/transactions/{transactionId}/ModifComment:
    patch:
        security:
        - Bearer: []
        tags:
        - User Module
        summary: Patch Transaction Comment
        description: API for modifying the comment of a specific transaction
        parameters:
        - in: path
            name: transactionId
            type: string
            required: true
            description: ID of the transaction
        - in: body
            name: body
            description: Modify Transaction Comment Payload
            required: true
            schema:
            $ref: '#/definitions/ModifyTransactionComment'
        responses:
        '200':
            description: Transaction comment modified successfully
            schema:
            $ref: '#/definitions/ModifyTransactionComment'
        '400':
            description: Invalid Fields
        '404':
            description: Transaction not found
        '500':
            description: Internal Server Error

  /user/transactions/{transactionId}:
    get:
        security:
        - Bearer: []
        tags:
        - User Module
        summary: Get Transaction by ID
        description: API for fetching details of a specific transaction by its ID
        parameters:
        - in: path
            name: transactionId
            type: string
            required: true
            description: ID of the transaction
        responses:
        '200':
            description: Transaction details retrieved successfully
            schema:
            $ref: '#/definitions/TransactionDetails'
        '400':
            description: Invalid Fields
        '404':
            description: Transaction not found
        '500':
            description: Internal Server Error


securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  TransactionWithId:  # Nouvelle définition pour inclure l'ID
    type: object
    properties:
      id:
        type: string
        description: Transaction ID
      amount:
        type: number
        description: Transaction amount
      description:
        type: string
        description: Transaction description
      date:
        type: string
        format: date
        description: Transaction date
      category:
        type: string
        description: Transaction category
      location:
        type: string
        description: Transaction location
      commentaire:
        type: string
        description: Commentaire de la transaction
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  AddTransactionComment:
    type: object
    properties:
      comment:
        type: string
        description: New comment for the transaction
  AddUpdateTransactionComment:
    type: object
    properties:
      comment:
        type: string
        description: Comment for the transaction
  ModifyTransactionComment:
    type: object
    properties:
      comment:
        type: string
        description: Modified comment for the transaction
  TransactionDetails:
    type: object
    properties:
      id:
        type: string
        description: Transaction ID
      amount:
        type: number
        description: Transaction amount
      description:
        type: string
        description: Transaction description
      date:
        type: string
        format: date
        description: Transaction date
      category:
        type: string
        description: Transaction category
      location:
        type: string
        description: Transaction location
      commentaire:
        type: string
        description: Commentaire de la transaction
